import matplotlib.pyplot as plt
import matplotlib.axes as axes


def plot_img_and_mask(img, img_normal, mask, normal_mask, result, normal_result):
    fig, ax = plt.subplots(2, 3)
    ax[0][0].set_title('Input image')
    ax[0][0].imshow(img)
    ax[0][1].set_title(f'Net output')
    ax[0][1].imshow(mask)
    ax[0][2].set_title(f'Reduce output')
    ax[0][2].imshow(result)
    ax[1][0].set_title(f'normal input')
    ax[1][0].imshow(img_normal)
    ax[1][1].set_title(f'normal output')
    ax[1][1].imshow(normal_mask)
    ax[1][2].set_title(f'normal result')
    ax[1][2].imshow(normal_result)
    ax.set_xticks([])
    ax.set_yticks([])
    plt.xticks([]), plt.yticks([])
    plt.axis('off')
    plt.show()


def plot_imgs_and_masks(images):
    fig, ax = plt.subplots(3, len(images))
    for i, img_package in enumerate(images):
        ax[0][i].set_title(img_package[3])
        ax[0][i].imshow(img_package[0])
        ax[1][i].set_title(f'Net output')
        ax[1][i].imshow(img_package[1])
        ax[2][i].set_title(f'Reduce output')
        ax[2][i].imshow(img_package[2])
    plt.xticks([]), plt.yticks([])
    plt.show()


def plot_four(images):
    fig, ax = plt.subplots(5, len(images))
    for i, img_package in enumerate(images):
        ax[0][i].set_title(img_package[5])
        ax[0][i].imshow(img_package[0])
        ax[1][i].set_title(f'0 output')
        ax[1][i].imshow(img_package[1])
        ax[2][i].set_title(f'TowNet output')
        ax[2][i].imshow(img_package[2])
        ax[3][i].set_title(f'1 output')
        ax[3][i].imshow(img_package[3])
        ax[4][i].set_title(f'Reduce origen output')
        ax[4][i].imshow(img_package[4])
    plt.xticks([]), plt.yticks([])
    plt.show()


def plot_five(images):
    fig, ax = plt.subplots(6, len(images))
    for i, img_package in enumerate(images):
        ax[0][i].set_title('Original')
        ax[0][i].imshow(img_package[0])
        ax[0][i].set_xticks([])
        ax[0][i].set_yticks([])
        ax[1][i].set_title(f'Net1')
        ax[1][i].imshow(img_package[1])
        ax[1][i].set_xticks([])
        ax[1][i].set_yticks([])
        ax[2][i].set_title(f'reduce1')
        ax[2][i].imshow(img_package[2])
        ax[2][i].set_xticks([])
        ax[2][i].set_yticks([])
        ax[3][i].set_title(f'Net2')
        ax[3][i].imshow(img_package[3])
        ax[3][i].set_xticks([])
        ax[3][i].set_yticks([])
        ax[4][i].set_title(f'reduce2')
        ax[4][i].imshow(img_package[4])
        ax[4][i].set_xticks([])
        ax[4][i].set_yticks([])
        ax[5][i].set_title(img_package[6], fontdict={'color': 'red'})
        ax[5][i].imshow(img_package[5])
        ax[5][i].set_xticks([])
        ax[5][i].set_yticks([])
    # plt.xticks([]), plt.yticks([])

    plt.show()

def plot_nine(images):
    fig, ax = plt.subplots(10, len(images))
    for i, img_package in enumerate(images):
        ax[0][i].imshow(img_package[0])
        ax[0][i].set_xticks([])
        ax[0][i].set_yticks([])
        ax[1][i].imshow(img_package[1])
        ax[1][i].set_xticks([])
        ax[1][i].set_yticks([])
        ax[2][i].imshow(img_package[2])
        ax[2][i].set_xticks([])
        ax[2][i].set_yticks([])
        ax[3][i].imshow(img_package[3])
        ax[3][i].set_xticks([])
        ax[3][i].set_yticks([])
        ax[4][i].imshow(img_package[4])
        ax[4][i].set_xticks([])
        ax[4][i].set_yticks([])
        ax[5][i].imshow(img_package[5])
        ax[5][i].set_xticks([])
        ax[5][i].set_yticks([])
        ax[6][i].imshow(img_package[6])
        ax[6][i].set_xticks([])
        ax[6][i].set_yticks([])
        ax[7][i].imshow(img_package[7])
        ax[7][i].set_xticks([])
        ax[7][i].set_yticks([])
        ax[8][i].imshow(img_package[8])
        ax[8][i].set_xticks([])
        ax[8][i].set_yticks([])
        ax[9][i].imshow(img_package[9])
        ax[9][i].set_xticks([])
        ax[9][i].set_yticks([])
    # plt.xticks([]), plt.yticks([])

    plt.show()
